### ISSUE TITLE
Invalid input data

### ISSUE THREAD

**Issue by slav123** [dbojdo/wFirma#22]
Mam problem z funkcją

`$invoice->addInvoiceContent(InvoicesContent::fromGoodId(GoodId::create(xxx), 1, 123, 23));`

 wszystko dzialalo i nagle "przestalo" - czy cos zmienilo sie w api ?

```
PHP Fatal error:  Uncaught Webit\WFirmaSDK\Entity\Exception\ValidationException: Invalid input data. in /vendor/webit/w-firma-api/src/Entity/Exception/ApiException.php:22
Stack trace:
#0 /vendor/webit/w-firma-api/src/Entity/Infrastructure/ResponseValidator.php(28): Webit\WFirmaSDK\Entity\Exception\ApiException::create(Object(Webit\WFirmaSDK\Entity\Request), Object(Webit\WFirmaSDK\Entity\Response))
#1 /vendor/webit/w-firma-api/src/Entity/Infrastructure/Buzz/BuzzRequestExecutor.php(77): Webit\WFirmaSDK\Entity\Infrastructure\ResponseValidator->validate(Object(Webit\WFirmaSDK\Entity\Request), Object(Webit\WFirmaSDK\Entity\Response))
#2 /vendor/webit/w-firma-api/src/Entity/DefaultEntityApi.php(31): Webit\WFirmaSDK\Entity\Infrastructure\Buzz\BuzzRequestExecutor->execute(Object(Webit\WFirmaSDK\Entity\Request))
#3 /vendor/webit/w-firma-api/src/Invoices/InvoicesApi.php(29): Webit\WFirmaSDK\Entity\D in /vendor/webit/w-firma-api/src/Entity/Exception/ApiException.php on line 22

Fatal error: Uncaught Webit\WFirmaSDK\Entity\Exception\ValidationException: Invalid input data. in /vendor/webit/w-firma-api/src/Entity/Exception/ApiException.php:22
Stack trace:
#0 /vendor/webit/w-firma-api/src/Entity/Infrastructure/ResponseValidator.php(28): Webit\WFirmaSDK\Entity\Exception\ApiException::create(Object(Webit\WFirmaSDK\Entity\Request), Object(Webit\WFirmaSDK\Entity\Response))
#1 /vendor/webit/w-firma-api/src/Entity/Infrastructure/Buzz/BuzzRequestExecutor.php(77): Webit\WFirmaSDK\Entity\Infrastructure\ResponseValidator->validate(Object(Webit\WFirmaSDK\Entity\Request), Object(Webit\WFirmaSDK\Entity\Response))
#2 /vendor/webit/w-firma-api/src/Entity/DefaultEntityApi.php(31): Webit\WFirmaSDK\Entity\Infrastructure\Buzz\BuzzRequestExecutor->execute(Object(Webit\WFirmaSDK\Entity\Request))
#3 /vendor/webit/w-firma-api/src/Invoices/InvoicesApi.php(29): Webit\WFirmaSDK\Entity\D in /vendor/webit/w-firma-api/src/Entity/Exception/ApiException.php on line 22
```

 czy jest szansa na jakies ludzkie komunikaty bledow czy to samo api wypluwa takie opisowe informacje ?

**Comment by slav123** [comment]
sprawdzalem dla roznych `GoodId` oraz wersje z `$invoice->addInvoiceContent(InvoicesContent::fromName());` i tez sie sklada

**Comment by jacekkow** [comment]
Złap ten wyjątek i zrób na nim var_dump.

Gdzieś tam powinna być pełna odpowiedź z API (patrząc na sucho gdzieś w okolicach $e->apiResponse()->entity()).

**Comment by slav123** [comment]
cos takiego mnie poratowalo, dziekuje za wskazówki !
```
try
{
	$invoice = $api->add($invoice);
} catch (Exception $e)
{

	$errors = $e->apiResponse()->entity()->errors();
	echo $errors[0]->message();
	echo $e->getMessage();
	die();
}
```
